<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menu</title>
    <link rel="stylesheet" href="/css/menu.css">
<link rel="icon" type="image/x-icon" href="/favicon.ico">
</head>
<body>
        
    <header class="top-bar">
        <div class="logo">IFBA MEDICAL GROUP</div>
        <nav class="top-nav">
            
          
            <a href="/login">Sair</a>
        
        </nav>
    </header>

    
    <nav class="Menu_lateral">
        <div class="botao_expandir_menu">
            <i class="bi bi-list"></i>
        </div>
        <ul>
            <li class="itemMenu">
                <a href="#">
                    <span class="Icon"><i class="bi bi-house"></i></span>
                    <span class="txt-link">Home</span>
                </a>
            </li>
            <li class="itemMenu">
                <a href="/cadastroPessoa">
                    <span class="Icon"><i class="bi bi-file-person"></i></span>
                    <span class="txt-link">Cadastro Pessoa</span>
                </a>
            </li>
             <li class="itemMenu">
                <a href="/cadastroProfissional">
                    <span class="Icon"><i class="bi bi-file-person"></i></span>
                    <span class="txt-link">Cadastro Profissional</span>
                </a>
            </li>
            <li class="itemMenu">
                <a href="/agendamento">
                    <span class="Icon"><i class="bi bi-calendar-event"></i></span>
                    <span class="txt-link">Agendamento</span>
                </a>
            </li>
            <li class="itemMenu">
                <a href="/listarAgendamento">
                    <span class="Icon"><i class="bi bi-person-lines-fill"></i></span>
                    <span class="txt-link">Listar Agendamento</span>
                </a>
            </li>
            <li class="itemMenu">
                <a href="/listarProfissional">
                    <span class="Icon"><i class="bi bi-person-lines-fill"></i></span>
                    <span class="txt-link">Listar Profissional</span>
                </a>
            </li>
        </ul>
    </nav>
  
</body>
</html>
