@template.layout.main(content = @`

    <div class="home">
        <h1>Precisão e rapidez na entrega de exames.</h1>
    </div>

    <section class="section">
        <h2>Serviços</h2>
        <div class="services">
            <div class="card">
                <h3>🧪 Exames Clínicos</h3>
                <p>Checkup e outros exames de rotina.</p>
            </div>
            <div class="card">
                <h3>💉 Vacinação</h3>
                <p>Planos de vacinas para sua familia.</p>
            </div>
            <div class="card">
                <h3>🦷 Atendimento Odontológico</h3>
                <p>Mantenha os seus dentes sempre limpos e saudáveis</p>
            </div>
            <div class="card">
                <h3>🚨 Emergência</h3>
                <p>Emergência 24 horas.</p>
            </div>
            <div class="card">
                <h3>🩺 Consulta Médica Geral</h3>
                <p>Avaliação geral de saúde com orientação e encaminhamento para especialistas..</p>
            </div>
            <div class="card">
                <h3>🩹 Serviço de Curativo</h3>
                <p>Tratamento de feridas com técnicas seguras e materiais esterilizados..</p>
            </div>
        </div>
    </section>
`)